project:
  type: website

website:
  title: "api"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
    left:
      -href: codes.qmd
        text: "Téléchargement des codes"

format:
  ofce-html: default
editor: visual

